title: Jiawei Li
logo: /LJW_photo.png
description:
  - Postdoc@FUB
  - Email: jadeljw (at) gmail.com
social:
  - name: Bluesky
    url: https://bsky.app/profile/jiaweili.bsky.social
show_downloads: false
$ google_analytics:
theme: jekyll-theme-minimal
