title: Jiawei Li
logo: /LJW_photo.png
description: 
Post_doc Researcher
Neural Dynamics of Visual Cognition Group
Department of Education and Psychology
Freie Universität Berlin
show_downloads: false
$ google_analytics:
theme: jekyll-theme-minimal
