title: Jiawei Li
logo: /LJW_photo.png
description:
  - Postdoc
  - Neural Dynamics of Visual Cognition Group
  - Department of Education and Psychology
  - Freie Universität Berlin
  - Email: jadeljw (at) gmail.com
social:
  - name: Bluesky
    url: https://bsky.app/profile/jiaweili.bsky.social
show_downloads: false
$ google_analytics:
theme: jekyll-theme-minimal
