title: Jiawei Li
tagline: ""
logo: /LJW_photo.png
description: "Postdoc<br>Neural Dynamics of Visual Cognition Group<br>Department of Education and Psychology<br>Freie Universität Berlin<br>Email: jadeljw (at) gmail.com"
show_downloads: false
$ google_analytics:
theme: jekyll-theme-minimal
