title: Jiawei Li
logo: /LJW_photo.png
description: A post-doc researcher
description: Neural Dynamics of Visual Cognition Group
description: Department of Education and Psychology
description: Freie Universität Berlin
description: Email adress jadeljw At gmail doc com
show_downloads: false
$ google_analytics:
theme: jekyll-theme-minimal
